"""Shared Agent Bridge protocol contracts."""

from .identity import conversation_id as conversation_id
from .identity import provider_session_key as provider_session_key
from .identity import stable_id as stable_id
from .models import (
    SCHEMA_VERSION,
    AgentRef,
    ArtifactRef,
    AuthorityLimits,
    AuthorityUsage,
    AutonomyMode,
    Availability,
    BridgeEnvelope,
    CapabilityAdvertisement,
    CapabilityRef,
    CollaborationMessage,
    CollaborationOperation,
    CollaborationRoom,
    ConversationHandoff,
    ConversationRef,
    CoordinatorActivation,
    CoordinatorActivationStatus,
    CoordinatorIntake,
    CoordinatorIntakeStatus,
    CoordinatorRole,
    DeliveryPolicy,
    EndpointKind,
    EndpointRef,
    EnvironmentRef,
    ExecutionAttempt,
    ExecutionFailure,
    ExecutionLease,
    ExecutionOperation,
    ExecutionProgress,
    ExecutionRequest,
    ExecutionResult,
    ExecutionStatus,
    MessageKind,
    NodeHeartbeat,
    NodeRef,
    NodeRegistration,
    ProviderThreadRef,
    RegisteredEndpoint,
    Relationship,
    RepositoryRef,
    RoleCheckpoint,
    RoleConversationLink,
    RoleEvent,
    RoleLease,
    RoleReport,
    RoleRollupState,
    RoleStatus,
    WorkConversationLink,
    WorkItem,
    WorkRef,
    WorkRequest,
)

__all__ = [name for name in globals() if not name.startswith("_")]
